// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7e0rM7xoJHA1TrpOvrbLbgXsYJnYo0QA',
    appId: '1:958358226757:web:25a968e15c997a15ec202c',
    messagingSenderId: '958358226757',
    projectId: 'yallasafqa-1bbae',
    authDomain: 'yallasafqa-1bbae.firebaseapp.com',
    storageBucket: 'yallasafqa-1bbae.firebasestorage.app',
    measurementId: 'G-068T05T778',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJZvi3jDPdfR3SHjfW98YryKnOd6IJt7k',
    appId: '1:958358226757:android:3cd68a1f86bee365ec202c',
    messagingSenderId: '958358226757',
    projectId: 'yallasafqa-1bbae',
    storageBucket: 'yallasafqa-1bbae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqiqXlHnWy1N1r0Pr4Lz1Rs-9ccpEtPHg',
    appId: '1:958358226757:ios:b6d4ed8d5a8c368fec202c',
    messagingSenderId: '958358226757',
    projectId: 'yallasafqa-1bbae',
    storageBucket: 'yallasafqa-1bbae.firebasestorage.app',
    iosBundleId: 'com.example.yallaSafqa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqiqXlHnWy1N1r0Pr4Lz1Rs-9ccpEtPHg',
    appId: '1:958358226757:ios:b6d4ed8d5a8c368fec202c',
    messagingSenderId: '958358226757',
    projectId: 'yallasafqa-1bbae',
    storageBucket: 'yallasafqa-1bbae.firebasestorage.app',
    iosBundleId: 'com.example.yallaSafqa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7e0rM7xoJHA1TrpOvrbLbgXsYJnYo0QA',
    appId: '1:958358226757:web:8c64bd3bbcfb3ec1ec202c',
    messagingSenderId: '958358226757',
    projectId: 'yallasafqa-1bbae',
    authDomain: 'yallasafqa-1bbae.firebaseapp.com',
    storageBucket: 'yallasafqa-1bbae.firebasestorage.app',
    measurementId: 'G-FPNS74EVN3',
  );
}
